services:
  # SQL Server
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cashflow-sql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword!
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - cashflow-network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: cashflow-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - cashflow-network
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Transaction Service
  transaction-service:
    build:
      context: ../
      dockerfile: CashFlow.Transaction.API/Dockerfile
    container_name: cashflow-transaction-service
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__TransactionDatabase=Server=sql-server;Database=CashFlow.Transactions;User Id=sa;Password=YourStrongPassword!;TrustServerCertificate=True;
      - RabbitMQ__Host=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
      sql-server:
        condition: service_started
    networks:
      - cashflow-network

  # Consolidation Service
  consolidation-service:
    build:
      context: ../
      dockerfile: CashFlow.Consolidation.API/Dockerfile
    container_name: cashflow-consolidation-service
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ConsolidationDatabase=Server=sql-server;Database=CashFlow.Consolidation;User Id=sa;Password=YourStrongPassword!;TrustServerCertificate=True;
      - RabbitMQ__Host=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
      sql-server:
        condition: service_started
    networks:
      - cashflow-network

volumes:
  sqldata:
  rabbitmq_data:

networks:
  cashflow-network:
    driver: bridge